### PR TITLE
added duplicate shift button on the card component

### PR DESCRIPTION
**Pull request by aidaghf**

### CODE REVIEW

**Review by 13204767 — CHANGES_REQUESTED** [review]
Great work Aida! 

The button definitely works.

However, instead of duplicating it straight away, we should allow the shift modal to appear so that administrators can change the shift information straight away (e.g. Shift title, Venue, Start and End date etc.).

**Comment by aidaghf** [comment]
Thanks Brendon, that could be the job of 'Edit' button. I felt the process was long and repetitive.

**Comment by 13204767** [comment]
Hello Aida, 

What you are doing is correct. However, to minimise errors of accidentally duplicating shifts, we should produce a modal before the platform duplicates the shift.

1) User clicks on the duplicate icon
2) Edit Modal appears
3) User then changes the shift information. For example, changing the title from "Copy of Example Shift" to "Outreach Shift".

**Comment by aidaghf** [comment]
sure

**Review by 13204767 — APPROVED** [review]

**Pull request merged**
